export const parameters = [
    'url', 
    'access_key', 
    'viewport_width', 'viewport_height', 
    'device_scale_factor', 
    'image_quality', 
    'omit_background', 
    'format', 
    'full_page', 
    'block_ads', 
    'block_cookie_banners', 
    'block_trackers', 
    'block_banners_by_heuristics', 
    'cache', 'cache_ttl', 'cache_key', 
    'delay', 
    'timeout', 
    'wait_until', 
    'user_agent', 
    'authorization', 
    'headers', 
    'cookies', 
    'time_zone', 
] as const;

export const defaults = {
    url: 'https://adarshrkumar.dev', 
    access_key: 'Fqdz8P4VTnNBWg', 
    viewport_width: 1920, 
    viewport_height: 1080, 
    device_scale_factor: 1, 
    image_quality: 80, 
    omit_background: false, 
    format: 'jpg', 
    block_ads: true, 
    block_cookie_banners: true, 
    full_page: false, 
    block_trackers: true, 
    block_banners_by_heuristics: true, 
    cache: false, 
    cache_ttl: 0, 
    cache_key: '', 
    delay: 0, 
    timeout: 60, 
    wait_until: 'load,domcontentloaded', 
    user_agent: '', 
    authorization: '', 
    headers: '', 
    cookies: '', 
    time_zone: '',     
} as const; 